name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout rgbds
        uses: actions/checkout@master
        with:
          path: rgbds
          ref: v0.5.1
          repository: gbdev/rgbds

      - name: Install rgbds
        working-directory: rgbds
        run: |
          sudo make install

      - name: Remove rgbds
        run: |
          rm -rf rgbds

      - name: Compare
        run: |
          make DEBUG=1 -j$(nproc) compare
          if ! git diff-index --quiet HEAD --; then
            echo 'Uncommitted changes detected:'
            git diff-index HEAD --
            return 1
          fi

      - name: Discord webhook
        if: ${{ github.event_name == 'push' && github.repository_owner == 'pret' }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          .github/webhook.sh
