name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout rgbds
        uses: actions/checkout@master
        with:
          path: rgbds
          ref: v0.6.1
          repository: gbdev/rgbds

      - name: Install rgbds
        working-directory: rgbds
        run: |
          sudo make install

      - name: Remove rgbds
        run: |
          rm -rf rgbds

      - name: Compare
        if: ${{ github.repository_owner == 'pret' }}
        run: |
          make DEBUG=1 -j$(nproc) compare
          if ! git diff-index --quiet HEAD --; then
            echo 'Uncommitted changes detected:'
            git diff-index HEAD --
            return 1
          fi

      - name: Make
        if: ${{ github.repository_owner != 'pret' }}
        run: |
          make -j$(nproc)
          if ! git diff-index --quiet HEAD --; then
            echo 'Uncommitted changes detected:'
            git diff-index HEAD --
            return 1
          fi

      - name: Discord webhook
        if: ${{ github.event_name == 'push' && github.repository_owner == 'pret' }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          .github/webhook.sh

      - name: Checkout symbols
        if: ${{ github.event_name == 'push' && github.repository_owner == 'pret' }}
        uses: actions/checkout@master
        with:
          path: symbols
          ref: symbols

      - name: Move symbols
        if: ${{ github.event_name == 'push' && github.repository_owner == 'pret' }}
        run: |
          cp -v *.sym symbols/

      - name: Update symbols
        if: ${{ github.event_name == 'push' && github.repository_owner == 'pret' }}
        uses: EndBug/add-and-commit@v7
        with:
          branch: symbols
          cwd: "./symbols"
          add: "*.sym"
          message: ${{ github.event.commits[0].message }}
